import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { createContentFixture } from "./helpers/content-fixture.mjs";

test("projects schema-v2 catalogs from canonical snapshot identities", async () => {
  const { buildCatalogSnapshot } = await import("../src/lib/server/content/build-catalog.server.ts");
  const snapshot = await buildCatalogSnapshot({ repositoryRoot: await createContentFixture() });
  const skillCatalog = snapshot.skillCatalogV2();
  const recipeCatalog = snapshot.recipeCatalogV2();

  assert.equal(skillCatalog.schemaVersion, 2);
  assert.equal(skillCatalog.siteUrl, "https://skills.lab.sa/");
  assert.equal(skillCatalog.licenseExpression, "MIT");
  assert.deepEqual(skillCatalog.skills[0], {
    index: 1,
    id: "https://skills.lab.sa/skills/example/",
    kind: "skill",
    name: "example",
    description: "Example folded description.",
    category: "testing",
    files: ["SKILL.md", "references/guide.md"],
    resources: { references: 1, scripts: 0, assets: 0, evals: 0 },
    detailUrl: "/skills/example/",
    canonicalUrl: "https://skills.lab.sa/skills/example/",
    markdownUrl: "https://skills.lab.sa/skills/example/index.md",
    sourceUrl: "https://github.com/labdotsa/skills/tree/master/skills/example",
    fileUrl: "https://github.com/labdotsa/skills/blob/master/skills/example/SKILL.md",
    licenseExpression: "MIT",
    licenseUrl: "https://skills.lab.sa/LICENSE.txt",
    contentDigest: snapshot.skills[0].source.contentDigest,
  });
  assert.equal(recipeCatalog.schemaVersion, 2);
  assert.equal(recipeCatalog.recipes[0].id, "https://skills.lab.sa/recipes/example/");
  assert.deepEqual(recipeCatalog.recipes[0].relatedSkills, ["example", "external", "imagegen"]);
});

test("returns exact-byte mirrors by stable canonical identity", async () => {
  const { buildCatalogSnapshot } = await import("../src/lib/server/content/build-catalog.server.ts");
  const repositoryRoot = await createContentFixture();
  const snapshot = await buildCatalogSnapshot({ repositoryRoot });
  const id = "https://skills.lab.sa/skills/example/";
  const expected = await readFile(path.join(repositoryRoot, "skills/example/SKILL.md"));

  const first = snapshot.markdownMirror(id);
  assert.deepEqual(Buffer.from(first.bytes), expected);
  assert.equal(first.contentDigest, snapshot.skillCatalogV2().skills[0].contentDigest);
  first.bytes[0] = 0;
  assert.deepEqual(Buffer.from(snapshot.markdownMirror(id).bytes), expected);
});

test("projects the human catalog from the same validated snapshot", async () => {
  const { buildCatalogSnapshot } = await import("../src/lib/server/content/build-catalog.server.ts");
  const { projectDocumentationCatalog } = await import("../src/lib/server/content/projections.ts");
  const snapshot = await buildCatalogSnapshot({ repositoryRoot: await createContentFixture() });

  assert.equal(
    projectDocumentationCatalog(snapshot),
    "<!-- Generated by scripts/generate-catalog.ts. Do not edit by hand. -->\n\n# Skill catalog\n\n| Skill | Description |\n| --- | --- |\n| [example](../skills/example/SKILL.md) | Example folded description. |\n",
  );
});
