import type { RecipeEntry, SkillEntry } from "$lib/domain/catalog.js";
import type { CatalogSnapshot } from "./build-catalog.server.js";
import {
	recipeCatalogV2Schema,
	skillCatalogV2Schema,
	type RecipeCatalogV2,
	type SkillCatalogV2,
} from "./public-schemas.js";

const siteUrl = "https://skills.lab.sa/" as const;
const repositoryUrl = "https://github.com/labdotsa/skills" as const;
const licenseExpression = "MIT" as const;
const licenseUrl = "https://skills.lab.sa/LICENSE.txt" as const;

export type PublicationIdentity = Readonly<{
	id: string;
	kind: "skill" | "recipe";
	slug: string;
	canonicalUrl: string;
	markdownUrl: string;
	sourceUrl: string;
	htmlPath: string;
	markdownPath: string;
}>;

export function publicationIdentities(skills: readonly SkillEntry[], recipes: readonly RecipeEntry[]) {
	return Object.freeze([
		...skills.map((skill) => skillIdentity(skill)),
		...recipes.map((recipe) => recipeIdentity(recipe)),
	]);
}

export function projectSkillCatalog(snapshot: CatalogSnapshot): SkillCatalogV2 {
	return deepFreeze(skillCatalogV2Schema.parse({
		schemaVersion: 2,
		siteUrl,
		repositoryUrl,
		licenseExpression,
		licenseUrl,
		installCommand: "npx skills add labdotsa/skills",
		skills: snapshot.skills.map((skill, index) => {
			const identity = skillIdentity(skill);
			return {
				index: index + 1,
				id: identity.id,
				kind: "skill",
				name: skill.name,
				description: skill.description,
				category: skill.category,
				files: [...skill.packageFiles],
				resources: skill.resourceCounts,
				detailUrl: `/skills/${encodeURIComponent(skill.slug)}/`,
				canonicalUrl: identity.canonicalUrl,
				markdownUrl: identity.markdownUrl,
				sourceUrl: identity.sourceUrl,
				fileUrl: `${repositoryUrl}/blob/master/skills/${encodeURIComponent(skill.slug)}/SKILL.md`,
				licenseExpression,
				licenseUrl,
				contentDigest: skill.source.contentDigest,
			};
		}),
	}));
}

export function projectRecipeCatalog(snapshot: CatalogSnapshot): RecipeCatalogV2 {
	return deepFreeze(recipeCatalogV2Schema.parse({
		schemaVersion: 2,
		siteUrl,
		repositoryUrl,
		licenseExpression,
		licenseUrl,
		recipes: snapshot.recipes.map((recipe, index) => {
			const identity = recipeIdentity(recipe);
			return {
				index: index + 1,
				id: identity.id,
				kind: "recipe",
				slug: recipe.slug,
				title: recipe.title,
				description: recipe.description,
				category: recipe.category,
				status: recipe.status,
				conversations: recipe.stages.length,
				relatedSkills: recipe.skillRequirements.map((requirement) => requirement.name),
				detailUrl: `/recipes/${encodeURIComponent(recipe.slug)}/`,
				canonicalUrl: identity.canonicalUrl,
				markdownUrl: identity.markdownUrl,
				sourceUrl: identity.sourceUrl,
				licenseExpression,
				licenseUrl,
				contentDigest: recipe.source.contentDigest,
			};
		}),
	}));
}

export function serializePublicJson(value: SkillCatalogV2 | RecipeCatalogV2) {
	return `${JSON.stringify(value, null, 2)}\n`;
}

export function projectDocumentationCatalog(snapshot: CatalogSnapshot) {
	const lines = [
		"<!-- Generated by scripts/generate-catalog.ts. Do not edit by hand. -->",
		"",
		"# Skill catalog",
		"",
	];
	if (snapshot.skills.length === 0) {
		lines.push("No stable skills have been published yet.");
	} else {
		lines.push("| Skill | Description |", "| --- | --- |");
		for (const skill of snapshot.skills) {
			lines.push(`| [${markdownCell(skill.name)}](../skills/${encodeURIComponent(skill.slug)}/SKILL.md) | ${markdownCell(skill.description)} |`);
		}
	}
	return `${lines.join("\n")}\n`;
}

function skillIdentity(skill: SkillEntry): PublicationIdentity {
	const encoded = encodeURIComponent(skill.slug);
	const canonicalUrl = `${siteUrl}skills/${encoded}/`;
	return Object.freeze({
		id: canonicalUrl,
		kind: "skill",
		slug: skill.slug,
		canonicalUrl,
		markdownUrl: `${siteUrl}skills/${encoded}/index.md`,
		sourceUrl: `${repositoryUrl}/tree/master/skills/${encoded}`,
		htmlPath: `skills/${skill.slug}/index.html`,
		markdownPath: `skills/${skill.slug}/index.md`,
	});
}

function recipeIdentity(recipe: RecipeEntry): PublicationIdentity {
	const encoded = encodeURIComponent(recipe.slug);
	const canonicalUrl = `${siteUrl}recipes/${encoded}/`;
	return Object.freeze({
		id: canonicalUrl,
		kind: "recipe",
		slug: recipe.slug,
		canonicalUrl,
		markdownUrl: `${siteUrl}recipes/${encoded}/index.md`,
		sourceUrl: `${repositoryUrl}/blob/master/recipes/${encoded}/RECIPE.md`,
		htmlPath: `recipes/${recipe.slug}/index.html`,
		markdownPath: `recipes/${recipe.slug}/index.md`,
	});
}

function deepFreeze<T>(value: T): T {
	if (value && typeof value === "object") {
		Object.freeze(value);
		for (const child of Object.values(value)) deepFreeze(child);
	}
	return value;
}

function markdownCell(value: string) {
	return value.replace(/\s+/g, " ").replaceAll("|", "\\|").trim();
}
