import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { readSkillCatalog } from "./lib/skill-catalog.mjs";
import { createMarkdownUrlResolver, renderMarkdown } from "./lib/markdown.mjs";
import { assertRecipeSiteCatalog, createRecipeSiteCatalog, readRecipeCatalog } from "./lib/recipe-catalog.mjs";
import { assertSiteCatalog, createSiteCatalog } from "./lib/site-catalog.mjs";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");
const sourceDirectory = path.join(repositoryRoot, "website");
const outputDirectory = path.join(repositoryRoot, "site");
const repositoryUrl = "https://github.com/labdotsa/skills";
const siteUrl = "https://labdotsa.github.io/skills/";
const installCommand = "npx skills add labdotsa/skills";
const checkOnly = process.argv.includes("--check");

const skills = await readSkillCatalog(repositoryRoot);
const catalog = assertSiteCatalog(createSiteCatalog(skills, { installCommand, repositoryUrl }));
const recipes = await readRecipeCatalog(repositoryRoot);
const recipeCatalog = assertRecipeSiteCatalog(createRecipeSiteCatalog(recipes, repositoryUrl));
const recipeCountLabel = `${recipeCatalog.recipes.length} ${recipeCatalog.recipes.length === 1 ? "recipe" : "recipes"}`;
const serializedCatalog = JSON.stringify(catalog, null, 2);
const safeInlineCatalog = serializedCatalog.replaceAll("<", "\\u003c");
const serializedRecipeCatalog = JSON.stringify(recipeCatalog, null, 2);
const safeInlineRecipeCatalog = serializedRecipeCatalog.replaceAll("<", "\\u003c");

const template = await readFile(path.join(sourceDirectory, "index.html"), "utf8");
const skillTemplate = await readFile(path.join(sourceDirectory, "skill.html"), "utf8");
const recipeTemplate = await readFile(path.join(sourceDirectory, "recipe.html"), "utf8");
const recipesTemplate = await readFile(path.join(sourceDirectory, "recipes.html"), "utf8");
const inlineDataPattern = /(<script id="skills-data" type="application\/json">)[\s\S]*?(<\/script>)/;
const inlineRecipeDataPattern = /(<script id="recipes-data" type="application\/json">)[\s\S]*?(<\/script>)/;

if (!inlineDataPattern.test(template)) {
  throw new Error('website/index.html is missing the <script id="skills-data" type="application/json"> data block.');
}
if (!inlineRecipeDataPattern.test(recipesTemplate)) {
  throw new Error('website/recipes.html is missing the <script id="recipes-data" type="application/json"> data block.');
}

const generatedHtml = template
  .replace(inlineDataPattern, (_, openingTag, closingTag) => `${openingTag}\n${safeInlineCatalog}\n    ${closingTag}`)
  .replace("<html", "<!-- Generated by scripts/build-site.mjs. Edit website/, not site/. -->\n<html");
const generatedRecipe = recipeTemplate.replace(
  "<html",
  "<!-- Generated by scripts/build-site.mjs. Edit website/, not site/. -->\n<html",
);
const generatedRecipes = recipesTemplate
  .replace(
    inlineRecipeDataPattern,
    (_, openingTag, closingTag) => `${openingTag}\n${safeInlineRecipeCatalog}\n    ${closingTag}`,
  )
  .replace("<html", "<!-- Generated by scripts/build-site.mjs. Edit website/, not site/. -->\n<html");

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function sourceFileUrl(skill, file) {
  const encodedPath = file.split("/").map(encodeURIComponent).join("/");
  return `${repositoryUrl}/blob/main/skills/${encodeURIComponent(skill.name)}/${encodedPath}`;
}

function renderSkillPage(skill, markdownSource) {
  const fileCountLabel = `${skill.files.length} ${skill.files.length === 1 ? "file" : "files"}`;
  const command = `${installCommand} --skill ${skill.name}`;
  const canonicalUrl = `${siteUrl}skills/${skill.name}/`;
  const fileList = skill.files
    .map((file, index) => {
      const kind = file === "SKILL.md" ? "root" : file.startsWith("references/") ? "reference" : "support";
      return `\n                <li data-kind="${kind}">\n                  <span>${String(index + 1).padStart(2, "0")}</span>\n                  <a href="${sourceFileUrl(skill, file)}"><code>${escapeHtml(file)}</code><span>Open ↗</span></a>\n                </li>`;
    })
    .join("");
  const relatedList = catalog.skills
    .filter((candidate) => candidate.name !== skill.name)
    .slice(0, 3)
    .map(
      (candidate) =>
        `<a href="../${encodeURIComponent(candidate.name)}/index.html"><span>${escapeHtml(candidate.name)}</span><span aria-hidden="true">→</span></a>`,
    )
    .join("\n                ");
  const markdownContent = renderMarkdown(markdownSource, {
    headingOffset: 1,
    resolveUrl: createMarkdownUrlResolver({ repositoryUrl, skillName: skill.name }),
  });

  const replacements = {
    "{{CANONICAL_URL}}": escapeHtml(canonicalUrl),
    "{{CATEGORY}}": escapeHtml(skill.category),
    "{{DESCRIPTION}}": escapeHtml(skill.description),
    "{{FILE_COUNT_LABEL}}": escapeHtml(fileCountLabel),
    "{{FILE_LIST}}": fileList,
    "{{INSTALL_COMMAND}}": escapeHtml(command),
    "{{MARKDOWN_CONTENT}}": markdownContent,
    "{{RELATED_LIST}}": relatedList,
    "{{SKILL_FILE_URL}}": escapeHtml(skill.fileUrl),
    "{{SKILL_NAME}}": escapeHtml(skill.name),
    "{{SOURCE_URL}}": escapeHtml(skill.sourceUrl),
  };

  let page = skillTemplate;
  for (const [token, value] of Object.entries(replacements)) page = page.replaceAll(token, value);
  if (/{{[A-Z_]+}}/.test(page)) throw new Error(`Unresolved template token in detail page for ${skill.name}.`);
  return page.replace("<html", "<!-- Generated by scripts/build-site.mjs. Edit website/, not site/. -->\n<html");
}

const outputs = new Map([
  ["index.html", generatedHtml],
  ["404.html", generatedHtml],
  ["recipes.html", generatedRecipes],
  ["recipe.html", generatedRecipe],
  ["recipes.json", `${serializedRecipeCatalog}\n`],
  ["skills.json", `${serializedCatalog}\n`],
  [
    "sitemap.xml",
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${siteUrl}</loc></url>\n  <url><loc>${siteUrl}recipes.html</loc></url>\n  <url><loc>${siteUrl}recipe.html</loc></url>\n${catalog.skills.map((skill) => `  <url><loc>${siteUrl}skills/${skill.name}/</loc></url>`).join("\n")}\n</urlset>\n`,
  ],
  ["robots.txt", `User-agent: *\nAllow: /\nSitemap: ${siteUrl}sitemap.xml\n`],
  [".nojekyll", ""],
]);

for (const skill of catalog.skills) {
  const markdownSource = await readFile(path.join(repositoryRoot, "skills", skill.name, "SKILL.md"), "utf8");
  outputs.set(`skills/${skill.name}/index.html`, renderSkillPage(skill, markdownSource));
}

for (const filename of ["catalog.js", "app.js", "copy.js", "recipes.js", "theme.js", "styles.css", "og.png"]) {
  outputs.set(filename, await readFile(path.join(sourceDirectory, filename)));
}

await mkdir(outputDirectory, { recursive: true });

if (checkOnly) {
  let stale = false;

  for (const [filename, expected] of outputs) {
    try {
      const current = await readFile(path.join(outputDirectory, filename));
      const expectedBuffer = Buffer.isBuffer(expected) ? expected : Buffer.from(expected);
      if (!current.equals(expectedBuffer)) {
        console.error(`site/${filename} is stale. Run \`npm run site:build\`.`);
        stale = true;
      }
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
      console.error(`site/${filename} is missing. Run \`npm run site:build\`.`);
      stale = true;
    }
  }

  if (stale) process.exit(1);
  console.log(`Discovery site is current for ${catalog.skills.length} skills and ${recipeCountLabel}.`);
} else {
  await rm(path.join(outputDirectory, "skills"), { recursive: true, force: true });
  for (const [filename, contents] of outputs) {
    await mkdir(path.dirname(path.join(outputDirectory, filename)), { recursive: true });
    await writeFile(path.join(outputDirectory, filename), contents);
  }
  console.log(`Built discovery site for ${catalog.skills.length} skills and ${recipeCountLabel}.`);
}
