import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { readSkillCatalog } from "./lib/skill-catalog.mjs";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");
const catalogPath = path.join(repositoryRoot, "docs", "catalog.md");
const checkOnly = process.argv.includes("--check");

function markdownCell(value) {
  return value.replace(/\s+/g, " ").replaceAll("|", "\\|").trim();
}

const skills = await readSkillCatalog(repositoryRoot);

const lines = [
  "<!-- Generated by scripts/generate-catalog.mjs. Do not edit by hand. -->",
  "",
  "# Skill catalog",
  "",
];

if (skills.length === 0) {
  lines.push("No stable skills have been published yet.");
} else {
  lines.push("| Skill | Description |", "| --- | --- |");
  for (const skill of skills) {
    lines.push(`| [${markdownCell(skill.name)}](../${skill.relativeSkillFile}) | ${markdownCell(skill.description)} |`);
  }
}

const generatedCatalog = `${lines.join("\n")}\n`;

if (checkOnly) {
  const currentCatalog = await readFile(catalogPath, "utf8");
  if (currentCatalog !== generatedCatalog) {
    console.error("docs/catalog.md is stale. Run `npm run catalog`.");
    process.exit(1);
  }
  console.log("Skill catalog is current.");
} else {
  await writeFile(catalogPath, generatedCatalog);
  console.log(`Wrote ${path.relative(repositoryRoot, catalogPath)}.`);
}
