import { access, readdir, readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { assertRecipeSiteCatalog } from "./lib/recipe-catalog.mjs";
import { assertSiteCatalog } from "./lib/site-catalog.mjs";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");
const sourceDirectory = path.join(repositoryRoot, "website");
const outputDirectory = path.join(repositoryRoot, "site");

const indexHtml = await readFile(path.join(outputDirectory, "index.html"), "utf8");
const notFoundHtml = await readFile(path.join(outputDirectory, "404.html"), "utf8");
const recipeHtml = await readFile(path.join(outputDirectory, "recipe.html"), "utf8");
const recipesHtml = await readFile(path.join(outputDirectory, "recipes.html"), "utf8");

if (indexHtml !== notFoundHtml) throw new Error("site/404.html must match the generated site shell.");
if (!indexHtml.includes("Generated by scripts/build-site.mjs")) {
  throw new Error("site/index.html is missing its generated-file marker.");
}
if (!indexHtml.includes('window.location.pathname.endsWith("/website/index.html")')) {
  throw new Error("The website source preview is missing its generated-site redirect.");
}
if (!recipeHtml.includes("Generated by scripts/build-site.mjs")) {
  throw new Error("site/recipe.html is missing its generated-file marker.");
}
if (!recipesHtml.includes("Generated by scripts/build-site.mjs")) {
  throw new Error("site/recipes.html is missing its generated-file marker.");
}
for (const [pageName, pageHtml] of [
  ["catalog", indexHtml],
  ["recipe index", recipesHtml],
  ["recipe detail", recipeHtml],
]) {
  if (!pageHtml.includes('src="./theme.js"') || !pageHtml.includes("data-theme-toggle")) {
    throw new Error(`The ${pageName} page is missing the shared theme control.`);
  }
}
if (!recipeHtml.includes("Four conversations, one shared workspace") || !recipeHtml.includes("Work one AFK issue per run")) {
  throw new Error("site/recipe.html is missing its core delivery structure.");
}
if (recipeHtml.includes("/Users/")) throw new Error("The public recipe contains a personal absolute path.");
for (const section of ["foundation", "visuals", "planning", "implementation"]) {
  if (!recipeHtml.includes(`id="${section}"`)) throw new Error(`The recipe is missing its ${section} conversation.`);
}
if (!indexHtml.includes('href="./recipes.html"')) throw new Error("The catalog navigation does not link to recipes.");
if (!recipeHtml.includes('href="./recipes.html"')) throw new Error("The recipe detail does not link back to recipes.");

const promptTargets = [...recipeHtml.matchAll(/data-copy-target="(#[^"]+)"/g)].map((match) => match[1]);
if (promptTargets.length < 9) throw new Error("The recipe must expose copyable prompts for every delivery phase.");
for (const target of promptTargets) {
  if (!recipeHtml.includes(`id="${target.slice(1)}"`)) throw new Error(`Recipe copy target ${target} does not exist.`);
}

const embeddedMatch = indexHtml.match(/<script id="skills-data" type="application\/json">([\s\S]*?)<\/script>/);
if (!embeddedMatch) throw new Error("site/index.html does not contain embedded catalog data.");

const embeddedCatalog = assertSiteCatalog(JSON.parse(embeddedMatch[1]));
const jsonCatalog = assertSiteCatalog(JSON.parse(await readFile(path.join(outputDirectory, "skills.json"), "utf8")));

if (JSON.stringify(embeddedCatalog) !== JSON.stringify(jsonCatalog)) {
  throw new Error("The embedded catalog and site/skills.json do not match.");
}

const embeddedRecipesMatch = recipesHtml.match(
  /<script id="recipes-data" type="application\/json">([\s\S]*?)<\/script>/,
);
if (!embeddedRecipesMatch) throw new Error("site/recipes.html does not contain embedded recipe data.");

const embeddedRecipes = assertRecipeSiteCatalog(JSON.parse(embeddedRecipesMatch[1]));
const jsonRecipes = assertRecipeSiteCatalog(
  JSON.parse(await readFile(path.join(outputDirectory, "recipes.json"), "utf8")),
);
if (JSON.stringify(embeddedRecipes) !== JSON.stringify(jsonRecipes)) {
  throw new Error("The embedded recipe catalog and site/recipes.json do not match.");
}
const homeRecipesMatch = indexHtml.match(
  /<script id="recipes-data" type="application\/json">([\s\S]*?)<\/script>/,
);
if (!homeRecipesMatch) throw new Error("site/index.html does not contain embedded recipe data.");
if (JSON.stringify(assertRecipeSiteCatalog(JSON.parse(homeRecipesMatch[1]))) !== JSON.stringify(jsonRecipes)) {
  throw new Error("The homepage recipe catalog and site/recipes.json do not match.");
}
if (!indexHtml.includes('data-directory-kind="skills"') || !indexHtml.includes('data-directory-kind="recipes"')) {
  throw new Error("The homepage does not expose the Skills and Recipes directory tabs.");
}
if (!recipesHtml.includes('src="./recipes.js"')) throw new Error("The recipe index does not load recipes.js.");
if (recipesHtml.includes("/Users/")) throw new Error("The public recipe index contains a personal absolute path.");

for (const recipe of embeddedRecipes.recipes) {
  const detailPath = path.join(outputDirectory, recipe.detailUrl.slice(2));
  await access(detailPath);
}

for (const filename of ["catalog.js", "app.js", "copy.js", "recipes.js", "theme.js", "styles.css", "og.png"]) {
  const [source, output] = await Promise.all([
    readFile(path.join(sourceDirectory, filename)),
    readFile(path.join(outputDirectory, filename)),
  ]);
  if (!source.equals(output)) throw new Error(`site/${filename} does not match website/${filename}.`);
}

for (const asset of ["./catalog.js", "./app.js", "./copy.js", "./theme.js", "./styles.css"]) {
  if (!indexHtml.includes(asset)) throw new Error(`site/index.html does not reference ${asset}.`);
}

for (const skill of embeddedCatalog.skills) {
  for (const file of skill.files) {
    await access(path.join(repositoryRoot, "skills", skill.name, file));
  }

  const detailPath = path.join(outputDirectory, "skills", skill.name, "index.html");
  const detailHtml = await readFile(detailPath, "utf8");
  if (!detailHtml.includes("Generated by scripts/build-site.mjs")) {
    throw new Error(`The detail page for ${skill.name} is missing its generated-file marker.`);
  }
  if (!detailHtml.includes(`<h1>${skill.name}</h1>`)) {
    throw new Error(`The detail page for ${skill.name} is missing its title.`);
  }
  if (!detailHtml.includes("../../styles.css") || !detailHtml.includes("../../copy.js") || !detailHtml.includes("../../theme.js")) {
    throw new Error(`The detail page for ${skill.name} is missing shared assets.`);
  }
  if (!detailHtml.includes('class="markdown-body"') || !detailHtml.includes("Skill instructions")) {
    throw new Error(`The detail page for ${skill.name} is missing rendered Markdown.`);
  }
  if (!detailHtml.includes("Related skills &amp; recipes") || !detailHtml.includes("related-directory")) {
    throw new Error(`The detail page for ${skill.name} is missing its related directory.`);
  }
  if (!detailHtml.includes('href="../../recipes.html"')) {
    throw new Error(`The detail page for ${skill.name} does not link to recipes.`);
  }
  if (/{{[A-Z_]+}}/.test(detailHtml)) {
    throw new Error(`The detail page for ${skill.name} contains an unresolved template token.`);
  }
}

const generatedSkillDirectories = (await readdir(path.join(outputDirectory, "skills"), { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();
const expectedSkillDirectories = embeddedCatalog.skills.map((skill) => skill.name).sort();
if (JSON.stringify(generatedSkillDirectories) !== JSON.stringify(expectedSkillDirectories)) {
  throw new Error("Generated detail-page directories do not match the public catalog.");
}

const sitemap = await readFile(path.join(outputDirectory, "sitemap.xml"), "utf8");
if (!sitemap.includes("https://skills.lab.sa/recipes.html")) {
  throw new Error("The sitemap does not include the recipe index.");
}
if (!sitemap.includes("https://skills.lab.sa/recipe.html")) {
  throw new Error("The sitemap does not include the recipe page.");
}

console.log(
  `Generated site contract is valid for ${embeddedCatalog.skills.length} skills and ${embeddedRecipes.recipes.length} ${embeddedRecipes.recipes.length === 1 ? "recipe" : "recipes"}.`,
);
